### ISSUE TITLE
MySQL Issues

### ISSUE THREAD

**Issue by kalepail** [zhelton/Barebones#1]
Not the worst start. Ideally though your theme would live all within the theme directory and not add stuff to the root of the project. We'll ignore that for now though.

Can you include a single MySQL query to run to create the table and all the appropriate columns? My guess is I've set up the wrong column types or something.

![screen shot 2018-12-01 at 3 39 24 pm](https://user-images.githubusercontent.com/4383610/49332674-883ab280-f57f-11e8-9421-f1da5904bc96.png)
![screen shot 2018-12-01 at 3 39 04 pm](https://user-images.githubusercontent.com/4383610/49332676-8b35a300-f57f-11e8-8313-e54d039b4a0b.png)

**Comment by zhelton** [comment]
Okay, I've added file which when included creates the table: create_table.php
